//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package ep;

import android.util.Base64;
import dy.x;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.Signature;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import kotlin.collections.l;

public final class a {
    private static final char[] HEX_CHARS;

    static {
        char[] hexCharacterArray = "0123456789abcdef".toCharArray();
        x.h(hexCharacterArray, "this as java.lang.String).toCharArray()");
        HEX_CHARS = hexCharacterArray;
    }

    /**
     * Computes SHA-256 hash of the input data
     * @param inputData The byte array to hash
     * @return SHA-256 hash as byte array, or null if algorithm not available
     */
    public static final byte[] a(byte[] inputData) {
        x.i(inputData, "<this>");

        try {
            MessageDigest sha256Digest = MessageDigest.getInstance("SHA-256");
            sha256Digest.update(inputData);
            inputData = sha256Digest.digest();
        } catch (NoSuchAlgorithmException algorithmException) {
            l10.a.a.e(algorithmException);
            inputData = null;
        }

        return inputData;
    }

    /**
     * Computes HMAC-SHA256 of the input data using the provided key
     * @param hmacKey The key for HMAC computation
     * @param dataToSign The string data to sign
     * @return HMAC-SHA256 signature as byte array, or null if error occurs
     */
    public static final byte[] b(byte[] hmacKey, String dataToSign) {
        x.i(dataToSign, "data");
        Object nullReference = null;

        try {
            Mac hmacSha256 = Mac.getInstance("HmacSHA256");
            SecretKeySpec secretKey = new SecretKeySpec(hmacKey, "HmacSHA256");
            hmacSha256.init(secretKey);
            Charset utf8Charset = StandardCharsets.UTF_8;
            x.h(utf8Charset, "UTF_8");
            hmacKey = dataToSign.getBytes(utf8Charset);
            x.h(hmacKey, "this as java.lang.String).getBytes(charset)");
            hmacKey = hmacSha256.doFinal(hmacKey);
        } catch (NoSuchAlgorithmException algorithmException) {
            l10.a.a.e(algorithmException);
            hmacKey = (byte[])nullReference;
        } catch (InvalidKeyException keyException) {
            l10.a.a.e(keyException);
            hmacKey = (byte[])nullReference;
        }

        return hmacKey;
    }

    /**
     * Signs data using a private key with the specified algorithm
     * @param dataToSign The byte array to sign
     * @param signatureAlgorithm The signature algorithm (e.g., "SHA256withRSA")
     * @param signingPrivateKey The private key for signing
     * @return Digital signature as byte array
     */
    public static final byte[] c(byte[] dataToSign, String signatureAlgorithm, PrivateKey signingPrivateKey) {
        x.i(dataToSign, "<this>");
        x.i(signatureAlgorithm, "yourAlgorithm");
        x.i(signingPrivateKey, "privateKey");
        
        try {
            Signature digitalSignature = Signature.getInstance(signatureAlgorithm);
            digitalSignature.initSign(signingPrivateKey);
            digitalSignature.update(dataToSign);
            dataToSign = digitalSignature.sign();
            x.h(dataToSign, "sign()");
        } catch (Exception signatureException) {
            l10.a.a.e(signatureException);
            dataToSign = null;
        }
        
        return dataToSign;
    }

    /**
     * Convenience method for signing with default SHA256withRSA algorithm
     * This is the synthetic method generated by Kotlin compiler for default parameters
     * @param dataToSign The byte array to sign
     * @param signatureAlgorithm The signature algorithm (if null, defaults to "SHA256withRSA")
     * @param signingPrivateKey The private key for signing
     * @param defaultFlags Flags indicating which parameters should use defaults (bit 0x1 for algorithm)
     * @param unusedParameter Unused synthetic parameter for Kotlin compatibility
     * @return Digital signature as byte array
     */
    public static final byte[] d(byte[] dataToSign, String signatureAlgorithm, PrivateKey signingPrivateKey, int defaultFlags, Object unusedParameter) {
        // Check if bit 0x1 is set, indicating algorithm should use default
        if ((defaultFlags & 0x1) != 0) {
            signatureAlgorithm = "SHA256withRSA";
        }
        
        return c(dataToSign, signatureAlgorithm, signingPrivateKey);
    }

    /**
     * Encodes byte array to Base64 string without wrapping
     * @param bytesToEncode The byte array to encode
     * @return Base64 encoded string
     */
    public static final String e(byte[] bytesToEncode) {
        x.i(bytesToEncode, "<this>");
        String base64String = Base64.encodeToString(bytesToEncode, Base64.NO_WRAP);
        x.h(base64String, "encodeToString(this, Base64.NO_WRAP)");
        return base64String;
    }

    /**
     * Converts byte array to lowercase hexadecimal string
     * @param bytesToConvert The byte array to convert to hex
     * @return Lowercase hex string representation, or empty string if input is null/empty
     */
    public static final String f(byte[] bytesToConvert) {
        if (bytesToConvert != null) {
            int arrayLength = bytesToConvert.length;
            int byteIndex = 0;
            boolean isEmpty;
            if (arrayLength == 0) {
                isEmpty = true;
            } else {
                isEmpty = false;
            }

            if (!isEmpty) {
                char[] hexCharArray = new char[bytesToConvert.length * 2];
                int totalBytes = bytesToConvert.length;

                for(arrayLength = 0; byteIndex < totalBytes; ++arrayLength) {
                    int currentByte = bytesToConvert[byteIndex] & 255;
                    int hexIndex = arrayLength * 2;
                    char[] hexChars = HEX_CHARS;
                    hexCharArray[hexIndex] = hexChars[currentByte / 16];
                    hexCharArray[hexIndex + 1] = hexChars[currentByte % 16];
                    ++byteIndex;
                }

                return l.q0(hexCharArray, "", (CharSequence)null, (CharSequence)null, 0, (CharSequence)null, (cy.l)null, 62, (Object)null);
            }
        }

        return "";
    }
}