#:schema node_modules/wrangler/config-schema.json
name = "roam-backend"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[placement]
mode = "smart"

[triggers]
crons = ["* * * * *"]
[[kv_namespaces]]
binding = "ROAM_KV"
id = "76a07aba72194475a5d6c33c147718a4"

[vars]
ROAM_BUNDLE_ID = "com.msdrigg.roam"

[[r2_buckets]]
binding = 'ROAM_DIAGNOSTIC_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'roam-diagnostics'
