#:schema node_modules/wrangler/config-schema.json
name = "roam-backend"
main = "src/index.ts"
compatibility_date = "2024-04-05"
logpush = true

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "ROAM_KV"
id = "76a07aba72194475a5d6c33c147718a4"

[vars]
ROAM_BUNDLE_ID = "com.msdrigg.roam"

[[r2_buckets]]
binding = 'ROAM_DIAGNOSTIC_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'roam-diagnostics'

[[durable_objects.bindings]]
name = "APNS_DURABLE_OBJECT"
class_name = "APNSDurableObject"

[[migrations]]
tag = "v1"                          # Should be unique for each entry
new_classes = ["APNSDurableObject"]

[[migrations]]
tag = "v2"
renamed_classes = [
    { from = "APNSDurableObject", to = "InternalDurableObject" },
] # Array of rename directives
