# fly.toml app configuration file generated for roam-backend-gateway on 2024-05-25T20:07:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'roam-backend-gateway'
primary_region = 'iad'

[build]

[[vm]]
size = 'shared-cpu-1x'
