title: Roam App # the main title

tagline: A user-focused Roku remote # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  A minimal, responsive, and featureful roku remote for macOS, iOS and watchOS
theme: minima
