title: Roam App # the main title

tagline: A user-focused Roku remote # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  A minimal, responsive, and featureful roku remote for macOS, iOS and watchOS

# theme: jekyll-theme-tactile
remote_theme: abhinavs/moonwalk
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  show_description: true # show blog description
  show_footer: false # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
