name: Archive Xcode Build on Push
"on":
    push:
        branches:
            - main

jobs:
    archive:
        runs-on: macos-14
        name: Archive Xcode Build
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Install Secret
              run: |
                  mkdir -p "./.private_keys" && \
                  echo "${{ secrets.XCODE_API_SECRET }}" > ./.private_keys/AuthKey_${{secrets.XCODE_API_KEY}}.p8

            - name: Fetch Tags
              run: |
                  git fetch --tags origin && \
                  git describe --tags

            - name: Archive
              run: |
                  ./scripts/export.py --archive --platform iOS macOS visionOS --github-actions
              env:
                  XCODE_API_KEY: "${{ secrets.XCODE_API_KEY }}"
                  XCODE_API_ISSUER: "${{ secrets.XCODE_API_ISSUER }}"
